apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gotaskq
  labels:
    app: gotaskq
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gotaskq
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
